GET http://localhost:3000

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users 
Content-Type: application/json
{

}

###

PUT http://localhost:3000/users/:id

###

DELETE http://localhost:3000/users/:id

###

GET http://localhost:3000/users/:userId/pedido/:pedidoId